/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.helloweenvsfei.struts.form.HelloForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-11-2017
 * 
 * XDoclet definition:
 * @struts.action path="/hello" name="helloForm" input="/form/hello.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/form/helloSuccess.jsp"
 */
public class HelloAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HelloForm helloForm = (HelloForm) form;
		//等同于 request.getParameter("name")。Struts将表单封装成HelloForm对象，并自动完成属性赋值，在action中直接使用即可
		if(helloForm.getName()==null	//如果没有输入name 
				|| helloForm.getName().trim().length()==0){
			return mapping.getInputForward();
		}
		//转到success页面，也就是 /form/helloSuccess.jsp 配置在 struts-config.xml中
		return mapping.findForward("success");
	}
}